require: rubocop-rspec

AllCops:
  NewCops: enable

Layout/CaseIndentation:
  IndentOneStep: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

RSpec/ExampleLength:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - '**/Gemfile'

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - '**/Gemfile'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
